# Generated by Django 6.1.1 on 2026-09-26 18:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    # No new table, so no RLS work: `web_form` already carries its policy, and
    # the M2M through table has no org_id column, like `notify_profiles`'.
    # Profile comes in through 0001's dependency on common.
    dependencies = [
        ("webforms", "0003_ticket_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="webform",
            name="assignment_mode",
            field=models.CharField(
                choices=[
                    ("person", "One person"),
                    ("rotation", "Rotate between members"),
                ],
                default="person",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="webform",
            name="rotation_cap",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="webform",
            name="rotation_last_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="common.profile",
            ),
        ),
        migrations.AddField(
            model_name="webform",
            name="rotation_members",
            field=models.ManyToManyField(
                blank=True, related_name="webforms_rotated", to="common.profile"
            ),
        ),
    ]
