# Generated by Django 6.1.1 on 2026-09-26 14:51

from django.db import migrations, models

import invoices.models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0011_document_number_unique_per_org"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimate",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[invoices.models.validate_tax_rate],
                verbose_name="Tax Rate (%)",
            ),
        ),
        migrations.AlterField(
            model_name="estimatelineitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[invoices.models.validate_tax_rate],
                verbose_name="Tax Rate (%)",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="shipping_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[invoices.models.validate_shipping_amount],
                verbose_name="Shipping",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[invoices.models.validate_tax_rate],
                verbose_name="Tax Rate (%)",
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[invoices.models.validate_tax_rate],
                verbose_name="Tax Rate (%)",
            ),
        ),
        migrations.AlterField(
            model_name="recurringinvoice",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[invoices.models.validate_tax_rate],
                verbose_name="Tax Rate (%)",
            ),
        ),
        migrations.AlterField(
            model_name="recurringinvoicelineitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[invoices.models.validate_tax_rate],
                verbose_name="Tax Rate (%)",
            ),
        ),
    ]
