# Generated by Django 6.1.1 on 2026-09-27 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0012_tax_rate_and_shipping_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimate",
            name="issue_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Issue Date"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Issue Date"
            ),
        ),
        migrations.AlterField(
            model_name="recurringinvoice",
            name="next_generation_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                verbose_name="Next Generation Date",
            ),
        ),
        migrations.AlterField(
            model_name="recurringinvoice",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Start Date"
            ),
        ),
    ]
