# Generated by Django 6.1.1 on 2026-09-26 13:17

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql

# Registered in common/rls/__init__.py:ORG_SCOPED_TABLES.
TABLE = "saved_view"


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql(TABLE))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql(TABLE))


class Migration(migrations.Migration):
    # RLS policy creation cannot run inside an atomic block.
    atomic = False

    dependencies = [
        ("common", "0043_org_help_center"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("leads", "Leads"),
                            ("contacts", "Contacts"),
                            ("accounts", "Accounts"),
                            ("opportunities", "Deals"),
                            ("cases", "Tickets"),
                            ("invoices", "Invoices"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to="common.profile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "saved_view",
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        fields=["org", "-created_at"],
                        name="saved_view_org_id_77a76d_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("profile"),
                        models.F("module"),
                        django.db.models.functions.text.Lower("name"),
                        name="saved_view_name_ci_unique",
                    )
                ],
            },
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
