# Generated by Django 6.1.1 on 2026-09-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0047_calendar_feed_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityauditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILURE", "Login Failure"),
                    ("LOGOUT", "Logout"),
                    ("ORG_SWITCH", "Organization Switch"),
                    ("TOKEN_REFRESH", "Token Refresh"),
                    ("TOKEN_REVOKED", "Token Revoked"),
                    ("PERMISSION_DENIED", "Permission Denied"),
                    ("CROSS_ORG_ATTEMPT", "Cross-Org Access Attempt"),
                    ("API_KEY_USED", "API Key Used"),
                    ("API_KEY_INVALID", "Invalid API Key"),
                    ("MEMBERSHIP_REVOKED", "Membership Revoked"),
                    ("SUSPICIOUS_ACTIVITY", "Suspicious Activity"),
                    ("SAMPLE_DATA_CLEARED", "Vertical Pack Sample Data Cleared"),
                    ("WEBHOOK_PAUSED", "Webhook Paused"),
                    ("WEBHOOK_REENABLED", "Webhook Re-enabled"),
                    ("WEBHOOK_CHANGED", "Webhook Destination Changed"),
                    ("RECORD_MERGED", "Record Merged"),
                    ("CALENDAR_FEED_ENABLED", "Calendar Feed Enabled"),
                    ("CALENDAR_FEED_REGENERATED", "Calendar Feed Regenerated"),
                    ("CALENDAR_FEED_DISABLED", "Calendar Feed Disabled"),
                    ("API_TOKEN_CREATED", "API Token Created"),
                    ("API_TOKEN_REVOKED", "API Token Revoked"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
