# Generated by Django 6.1.1 on 2026-09-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0049_portal_token_inbound_mailbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="default_currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD, Dollar"),
                    ("EUR", "EUR, Euro"),
                    ("GBP", "GBP, Pound"),
                    ("INR", "INR, Rupee"),
                    ("CAD", "CAD, Dollar"),
                    ("AUD", "AUD, Dollar"),
                    ("JPY", "JPY, Yen"),
                    ("CNY", "CNY, Yuan"),
                    ("CHF", "CHF, Franc"),
                    ("SGD", "SGD, Dollar"),
                    ("AED", "AED, Dirham"),
                    ("BRL", "BRL, Real"),
                    ("MXN", "MXN, Peso"),
                    ("ZAR", "ZAR, Rand"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
