# Generated by Django 6.1.1 on 2026-09-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0031_escalationpolicy_next_response_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundmailbox",
            name="topic_arn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SNS Topic ARN this mailbox accepts mail from. A valid SNS signature only proves a message came from some topic in some AWS account, so the webhook also requires this exact match. An admin can enter it. Left blank, it is pinned from the first verified SubscriptionConfirmation whose topic belongs to an AWS account listed in the INBOUND_SNS_ACCOUNT_IDS setting, and a topic in any other account pins nothing. Until it is set, every message is rejected.",
                max_length=256,
            ),
        ),
    ]
