# Generated by Django 6.0.7 on 2026-08-18 20:06

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0041_clear_stale_rls_force_flags"),
        ("leads", "0016_alter_leadpipeline_is_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingCampaign",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "primary_channel",
                    models.CharField(
                        choices=[
                            ("organic_search", "Organic search"),
                            ("paid_search", "Paid search"),
                            ("organic_social", "Organic social"),
                            ("paid_social", "Paid social"),
                            ("email", "Email"),
                            ("referral", "Referral"),
                            ("event", "Event"),
                            ("direct", "Direct"),
                            ("partner", "Partner"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_sample",
                    models.BooleanField(
                        default=False,
                        help_text="True only for demo rows created by common.packs.applier._apply_sample_data. Server-set exclusively, never expose this as a writable field on any serializer. It is the sole key common.packs.applier.clear_sample_data uses to decide what to delete, so a client-writable path here would let a user mark an arbitrary real record as sample and have it deleted.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_campaigns",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "marketing_campaign",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LeadAttributionTouch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "touch_type",
                    models.CharField(
                        choices=[
                            ("first", "First touch"),
                            ("assist", "Assisted touch"),
                            ("last", "Last touch"),
                        ],
                        max_length=8,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("source", models.CharField(max_length=100)),
                ("medium", models.CharField(blank=True, max_length=100)),
                ("campaign_key", models.CharField(blank=True, max_length=160)),
                ("content_key", models.CharField(blank=True, max_length=160)),
                ("term_key", models.CharField(blank=True, max_length=160)),
                ("landing_page_ref", models.CharField(blank=True, max_length=128)),
                ("referrer_domain", models.CharField(blank=True, max_length=253)),
                (
                    "lawful_basis",
                    models.CharField(
                        choices=[
                            ("consent", "Consent"),
                            ("legitimate_interest", "Legitimate interest"),
                            ("contract", "Contract or pre-contractual steps"),
                            ("legal_obligation", "Legal obligation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("privacy_notice_version", models.CharField(max_length=64)),
                ("consent_evidence_ref", models.CharField(blank=True, max_length=128)),
                ("idempotency_key_digest", models.CharField(max_length=64)),
                ("request_digest", models.CharField(max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribution_touches",
                        to="leads.lead",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_attribution_touches",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_touches",
                        to="leads.marketingcampaign",
                    ),
                ),
            ],
            options={
                "db_table": "lead_attribution_touch",
                "ordering": ("occurred_at", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="marketingcampaign",
            index=models.Index(
                fields=["org", "status", "-created_at"],
                name="marketing_c_org_id_9ccc9e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketingcampaign",
            index=models.Index(
                fields=["org", "primary_channel", "-created_at"],
                name="marketing_c_org_id_5cece8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketingcampaign",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                models.F("org"),
                name="unique_campaign_code_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketingcampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("starts_at__isnull", True),
                    ("ends_at__gte", models.F("starts_at")),
                    _connector="OR",
                ),
                name="campaign_end_not_before_start",
            ),
        ),
        migrations.AddIndex(
            model_name="leadattributiontouch",
            index=models.Index(
                fields=["org", "occurred_at"], name="lead_attrib_org_id_c4b054_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadattributiontouch",
            index=models.Index(
                fields=["lead", "touch_type", "occurred_at"],
                name="lead_attrib_lead_id_35815b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leadattributiontouch",
            index=models.Index(
                fields=["campaign", "occurred_at"],
                name="lead_attrib_campaig_b671c0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadattributiontouch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("touch_type", "first")),
                fields=("lead",),
                name="unique_first_touch_per_lead",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadattributiontouch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("touch_type", "last")),
                fields=("lead",),
                name="unique_last_touch_per_lead",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadattributiontouch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lawful_basis", "consent"), _negated=True),
                    models.Q(("consent_evidence_ref", ""), _negated=True),
                    _connector="OR",
                ),
                name="consent_requires_evidence_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadattributiontouch",
            constraint=models.UniqueConstraint(
                fields=("org", "idempotency_key_digest"),
                name="unique_attribution_idempotency_per_org",
            ),
        ),
    ]
