# Generated by Django 6.0.7 on 2026-08-19 02:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0042_rls_marketing_attribution"),
        ("leads", "0017_marketingcampaign_leadattributiontouch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("subject_ref_digest", models.CharField(max_length=64)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("access", "Access"),
                            ("correction", "Correction"),
                            ("deletion", "Deletion"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="submitted", editable=False, max_length=16
                    ),
                ),
                ("due_at", models.DateTimeField()),
                ("legal_hold", models.BooleanField(default=False, editable=False)),
                ("idempotency_key_digest", models.CharField(max_length=64)),
                ("request_digest", models.CharField(max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_subject_requests",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "data_subject_request",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["org", "status", "due_at"],
                        name="data_subjec_org_id_dc5402_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status", "submitted")),
                        name="dsr_intake_submitted_only",
                    ),
                    models.UniqueConstraint(
                        fields=("org", "idempotency_key_digest"),
                        name="unique_dsr_idempotency_per_org",
                    ),
                ],
            },
        ),
    ]
