# Generated by Django 6.0.7 on 2026-08-19 02:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0042_rls_marketing_attribution"),
        ("leads", "0018_datasubjectrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubjectRequestEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("identity_verified", "Identity verified"),
                            ("legal_hold_placed", "Legal hold placed"),
                            ("legal_hold_released", "Legal hold released"),
                            ("rejected", "Rejected without execution"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=32)),
                ("evidence_ref_digest", models.CharField(blank=True, max_length=64)),
                ("actor_ref_digest", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "data_subject_request_event",
                "ordering": ("sequence",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="datasubjectrequest",
            name="dsr_intake_submitted_only",
        ),
        migrations.AddField(
            model_name="datasubjectrequest",
            name="version",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="datasubjectrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("verified", "Identity verified"),
                    ("rejected", "Rejected without execution"),
                ],
                default="submitted",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="datasubjectrequestevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="datasubjectrequestevent",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_subject_request_events",
                to="common.org",
            ),
        ),
        migrations.AddField(
            model_name="datasubjectrequestevent",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="leads.datasubjectrequest",
            ),
        ),
        migrations.AddField(
            model_name="datasubjectrequestevent",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        migrations.AddConstraint(
            model_name="datasubjectrequestevent",
            constraint=models.UniqueConstraint(
                fields=("request", "sequence"), name="unique_dsr_event_sequence"
            ),
        ),
    ]
