# Generated by Django 6.0.7 on 2026-08-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0019_datasubjectrequestevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasubjectrequestevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("identity_verified", "Identity verified"),
                    ("legal_hold_placed", "Legal hold placed"),
                    ("legal_hold_released", "Legal hold released"),
                    ("rejected", "Rejected without execution"),
                    ("export_prepared", "Encrypted export prepared"),
                ],
                max_length=24,
            ),
        ),
    ]
