# Generated by Django 6.1.1 on 2026-09-26 18:49
#
# The two join tables (`macro_tags`, `macro_set_assignees`) carry no
# org_id, like every other M2M table here, so they take no RLS policy of their
# own: both ends are org-scoped rows, and the serializer admits only same-org
# profiles and tags.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0046_securityauditlog_record_merged"),
        ("macros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="macro",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="macros_tagging", to="common.tags"
            ),
        ),
        migrations.AddField(
            model_name="macro",
            name="set_assignees",
            field=models.ManyToManyField(
                blank=True, related_name="macros_assigning", to="common.profile"
            ),
        ),
        migrations.AddField(
            model_name="macro",
            name="set_priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Low", "Low"),
                    ("Normal", "Normal"),
                    ("High", "High"),
                    ("Urgent", "Urgent"),
                ],
                default="",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="macro",
            name="set_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("New", "New"),
                    ("Assigned", "Assigned"),
                    ("Pending", "Pending"),
                    ("Closed", "Closed"),
                    ("Rejected", "Rejected"),
                ],
                default="",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="macro",
            name="body",
            field=models.TextField(blank=True, default=""),
        ),
    ]
